### PR TITLE
Dockerfile for showing cows on Docker.

### PR DESCRIPTION
**Pull request by alexellis**
Adding Docker usage, because why not? 

* After cloning the repository Node.js is not needed to see the cows
* Entrypoint instruction lets you specific the cow number you want to see.
* Can also be pushed to the Docker Hub to get loads more attention for the project.

>@Docker may re-tweet this if they think it's fun.
> [Re-tweet of Raspberry PI on Docker](https://twitter.com/docker/status/722286615939432448)

**Building:**

```
$ docker build -t cows .
Sending build context to Docker daemon 550.4 kB
Step 1 : FROM mhart/alpine-node:4
 ---> bc374b5ad19d
Step 2 : RUN mkdir -p /code/
 ---> Running in cc370c2a5960
 ---> f072e7030bbc
Removing intermediate container cc370c2a5960
Step 3 : WORKDIR /code/
 ---> Running in fdd0c7558940
 ---> 6cd088de8d2e
Removing intermediate container fdd0c7558940
Step 4 : ADD package.json ./
 ---> 4e3bed7c9cb4
Removing intermediate container d06c81b7561c
Step 5 : ADD *.js ./
 ---> d4b4933cc1d8
Removing intermediate container 0eb595b378ba
Step 6 : ADD cows.txt ./
 ---> 9db3c5d9c756
Removing intermediate container 2e3f40768607
Step 7 : ENTRYPOINT node show_cow.js
 ---> Running in b11351132f2f
 ---> 81192ba5f26e
Removing intermediate container b11351132f2f
Successfully built 81192ba5f26e
```

**Running it:**

```
$ docker run cows 400
          /)  (\
     .-._((,~~.))_.-,
      `-.   @@   ,-'
        / ,n--n. \
(`'\   ( ( .__. ) )  /`')
 `.'"._ ) `----' (_,"`.'
   "._             _,"
      /            \
     (              )
     (`-.__    __.-')
      \   /`--'\   /
       ) /      \ (
      /._\      /_,\
```

```
$ docker run cows 423
               (__)
(__)           (oo)
(oo)      ______\/
-\/    /|      |
| |   * |______|
| |        ||
---        --
Cow Computer 
```

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I would suggest creating a `docker-cows` repository and push that to docker hub.

**Comment by sindresorhus** [comment]
Hah, cool idea, but as @SamVerschueren said, would be better as a separate repo. I'd be happy to link to it from here :)

**Comment by alexellis** [comment]
That's a shame guys. I figured since you had a .travis.yml file (which uses Docker) you would appreciate this addition. Have you considered adding a paragraph on contribution guideline to the README?

**Comment by alexellis** [comment]
Docker image is named  alexellis2/cows:

```
$ docker run alexellis2/cows 423
               (__)
(__)           (oo)
(oo)      ______\/
-\/    /|      |
| |   * |______|
| |        ||
---        --
Cow Computer
```

```
$ docker run alexellis2/cows 0
Enter cow number between [1-423]
```

[Docker hub link](https://hub.docker.com/r/alexellis2/cows/)

**Comment by sindresorhus** [comment]
> Have you considered adding a paragraph on contribution guideline to the README?

Nah, it's already visible in the file browser and when you open an issue you get a yellow box telling you to read it.

> Docker image is named alexellis2/cows:

Cool. I added a link to it in the readme: https://github.com/sindresorhus/cows/commit/c9ebd517a52acc7a24deb40aeb31a5acffac65b4 :)

> $ docker run alexellis2/cows 0
Enter cow number between [1-423]

Maybe return a random cow when no number is supplied.

**Pull request closed without merging**
